sudo: false
language: java
jdk:
- oraclejdk8
script:
- test/run.sh
notifications:
  slack:
    secure: t40SqPaRAN8o2z6bkvO9JyTg6PcLeD32uoWGvXlpFVenlcJXYFU7Tni7n1N8N8txo0kAAWEpkeBxuSUDRsLe078bhfD5xFjPKwgSSD4n2XnrEEP/WvU8LvTGv2yuZB3A7QbcqzI+nIDhm5mQvVhPuPbDDpgHMCQZCkJyyiFsYxAI1DPxWbs8gtC5rq8aHx5qTZQufE45TrquMmdJULQDWLgYCyt9oF5fOLfiKy0K38FMNw1X+YTjnGwunLb9f0PfYZTgRey4xUAsfjDKSJDpTVfnPOgPez7EwD2zInbQK0BetlbmGLujOxzDc6ZNGO/sPaNp6UMBjZoOLmXlxEpXSS/UcQox8VmdzuyRtnmQEkcpZgLiMhZTfwTzt+ydxCNEdv7VF7bC9ctuuYFhL2JCT1i9eVsOgnEQQ3sGRI6zvU360+MMKbm88/GZo6XLx2j/5GPka9Mi5JS2/Un0iaUPx7W1X/Bs8UQhOLKTbqR+HjJBzPzaZJ1t/9BB92xO8T//6oo2pqvRqZgLQqiFpTsMwDQH7/aZ89kBjXj8S3aT/pFO1UaxAsQo+x8AaCbzQ0xuVboFfQin9ZvQf/qSs77Dboyse8XlsvW/oVjZG2VGTZtGR89DhkZf6ain+d2zgPLaX5rpwwAvFRQlh0eMWQOuYDJQHr5zKH9H9ooeIVNu8es=
